name = "mcp-mfai-tools"
main = "../src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Enable observability and logging
[observability]
enabled = true

# KV namespace for OAuth sessions
[[kv_namespaces]]
binding = "OAUTH_KV"
id = "c6668cdb8dfc4f2abf67aab912b3fc27"

# Durable Objects binding
[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "MinimalMCP"

# Durable Object migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["MinimalMCP"]

# Environment variables
[vars]
DEBUG = "true"
# Development mode - NEVER set to "true" in production!
DEVELOPMENT_MODE = "false"
# Comma-separated lists of allowed users
ALLOWED_GITHUB_USERS = "danilopezmella,modflowai,tvejarf,tamvejarf,reneangermeyer,valeriarosselb,roh-sgm,sebaalday,BegoUr,Arielzs2610,NicoGavilio,Ernestopoti,ThiareGD,fcovaldivieso,julssD"
ALLOWED_GOOGLE_USERS = "daniel.lopez.me@gmail.com,admin@modflow.ai,zunigasm.ariel@gmail.com,vair.pointon@gmail.com,bheinle@barr.com,fcovaldivieso@gmail.com,saulmontoya@gmail.com,fzeladas@gmail.com,aria.tzhang@gmail.com,cetin.ekiz@gmail.com,testmodflowai@gmail.com"

# Secrets to set with wrangler secret put:
# MODFLOW_AI_MCP_01_CONNECTION_STRING
# GITHUB_CLIENT_ID (from your new GitHub OAuth app)
# GITHUB_CLIENT_SECRET (from your new GitHub OAuth app)
# GOOGLE_CLIENT_ID (from your new Google OAuth app)
# GOOGLE_CLIENT_SECRET (from your new Google OAuth app)
# COOKIE_ENCRYPTION_KEY (generate with: openssl rand -base64 32)